name: Testing
 
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"      
  pull_request:
    types: [ready_for_review, synchronize, opened]
    paths-ignore:
      - "README.md"

jobs:
  testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.4]

    name: Testing PHP${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Setup KSEFPublicKey
        run: |
          mkdir -p ./config/keys
          echo "${{ secrets.KSEF_PUBLIC_KEY }}" > ./config/keys/testPublicKey.pem

      - name: Setup Certificate
        run: |
          mkdir -p ./scripts
          mkdir -p ./config/certificates
          echo "${{ vars.SIGNATURE_NIP }}" > ./scripts/signature-nip.txt
          openssl req -newkey rsa:2048 -nodes -keyout "./config/certificates/key.pem" -out "./config/certificates/certificate.csr" -config ./scripts/signature-nip.txt
          openssl x509 -req -in "./config/certificates/certificate.csr" -signkey "./config/certificates/key.pem" -out "./config/certificates/certificate.crt"
          openssl pkcs12 -export -out "./config/certificates/certificate.p12" -inkey "./config/certificates/key.pem" -in "./config/certificates/certificate.crt" -passout pass:password

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run CS Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --allow-unsupported-php-version=yes

      - name: Run Rector
        run: ./vendor/bin/rector process --dry-run

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyse --error-format=github 

      - name: Run Pest
        run: ./vendor/bin/pest --parallel --ci